apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamshell-ssh-server.fullname" . }}
  labels:
    {{- include "teamshell-ssh-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceSSH.type }}
  ports:
    - port: {{ .Values.serviceSSH.port }}
      targetPort: {{ .Values.serviceSSH.port }}
      nodePort: {{ .Values.serviceSSH.nodePort}}
  selector:
    {{- include "teamshell-ssh-server.selectorLabels" . | nindent 4 }}
